AUTHOR_IMG = u'http://bruno.adele.im/static/bruno.jpg'
AUTHOR_LINK = u'http://bruno.adele.im'
AUTHOR_SUMMARY = u"Agé de 40 ans avec 20 ans d'expérience dans le développement et dans le réseau (y compris internet). Passionné d'informatique depuis son plus jeune âge, a un faible pour les logiciels libres. En recherche d'opportunité dans la région de Montpellier pour exercer sa passion, de préférence dans la R&D"
AUTHOR = u'Bruno Adel\xe9'
DEFAULT_LANG = u'fr'
DEFAULT_PAGINATION = 10
DISQUS_SITENAME = u'blogdejesuislibreorg'
FEED_ALL_ATOM = u'feed.atom'
FEED_DOMAIN = u'http://blog.jesuislibre.org'
GITHUB_BLOG_SITE = u'https://github.com/badele/blog.jesuislibre.org'
LINKS = ((u'Home', u'/'), (u'archives', u'/archives.html'), (u'tags', u'/tags.html'), (u'A propos', u'http://bruno.adele.im'))
SITENAME = u'Famille de geeks'
SITESUBTITLE = u'Une famille compl\xe8tement 633<'
SITEURL = u'http://blog.jesuislibre.org'
SOCIAL = ((u'adele', u'http://adele.im'), (u'feed', u'http://feeds.feedburner.com/FamilleDeGeek'), (u'twitter', u'http://twitter.com/jesuislibre.org'), (u'google+', u'https://plus.google.com/100723270029692582967'), (u'blog', u'http://blog.jesuislibre.org'), (u'facebook', u'http://www.facebook.com/bruno.adele'), (u'flickr', u'http://www.flickr.com/photos/b_adele'), (u'linkedin', u'http://fr.linkedin.com/in/brunoadele'))
